version: "3.8"

services:
  artemis:
    image: quay.io/artemiscloud/activemq-artemis-broker:artemis.2.28.0
    ports:
      - "8161:8161"
      - "61616:61616"
      - "5672:5672"
    environment:
      AMQ_USER: quarkus
      AMQ_PASSWORD: quarkus